//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.11 at 03:02:41 PM EDT 
//

package com.napoleoncs.keepass;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;

/**
 * <p>
 * Java class for Entry complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="Entry">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="UUID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="IconID" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *         &lt;element name="CustomIconUUID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ForegroundColor" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="BackgroundColor" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="OverrideURL" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Tags" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Times" type="{}Times" minOccurs="0"/>
 *         &lt;element name="String" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Key" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Value">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="ProtectInMemory" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="AutoType">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Enabled" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="DataTransferObfuscation" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="DefaultSequence" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Association" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Window" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="KeystrokeSequence" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="History">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Entry" type="{}Entry" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Entry", propOrder = { "uuid", "iconID", "customIconUUID",
		"foregroundColor", "backgroundColor", "overrideURL", "tags", "times",
		"string", "autoType", "history" })
public class Entry implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1839920941739571509L;
	
	@XmlElement(name = "UUID", required = true)
	protected java.lang.String uuid;
	@XmlElement(name = "IconID")
	protected byte iconID;
	@XmlElement(name = "CustomIconUUID", required = true)
	protected java.lang.String customIconUUID;
	@XmlElement(name = "ForegroundColor", required = true)
	protected java.lang.String foregroundColor;
	@XmlElement(name = "BackgroundColor", required = true)
	protected java.lang.String backgroundColor;
	@XmlElement(name = "OverrideURL", required = true)
	protected java.lang.String overrideURL;
	@XmlElement(name = "Tags", required = true)
	protected java.lang.String tags;
	@XmlElement(name = "Times")
	protected Times times;
	@XmlElement(name = "String")
	protected List<Entry.String> string;
	@XmlElement(name = "AutoType", required = true)
	protected Entry.AutoType autoType;
	@XmlElement(name = "History", required = true)
	protected Entry.History history;

	/**
	 * Gets the value of the uuid property.
	 * 
	 * @return possible object is {@link java.lang.String }
	 * 
	 */
	public java.lang.String getUUID() {
		return uuid;
	}

	/**
	 * Sets the value of the uuid property.
	 * 
	 * @param value
	 *            allowed object is {@link java.lang.String }
	 * 
	 */
	public void setUUID(java.lang.String value) {
		this.uuid = value;
	}

	/**
	 * Gets the value of the iconID property.
	 * 
	 */
	public byte getIconID() {
		return iconID;
	}

	/**
	 * Sets the value of the iconID property.
	 * 
	 */
	public void setIconID(byte value) {
		this.iconID = value;
	}

	/**
	 * Gets the value of the customIconUUID property.
	 * 
	 * @return possible object is {@link java.lang.String }
	 * 
	 */
	public java.lang.String getCustomIconUUID() {
		return customIconUUID;
	}

	/**
	 * Sets the value of the customIconUUID property.
	 * 
	 * @param value
	 *            allowed object is {@link java.lang.String }
	 * 
	 */
	public void setCustomIconUUID(java.lang.String value) {
		this.customIconUUID = value;
	}

	/**
	 * Gets the value of the foregroundColor property.
	 * 
	 * @return possible object is {@link java.lang.String }
	 * 
	 */
	public java.lang.String getForegroundColor() {
		return foregroundColor;
	}

	/**
	 * Sets the value of the foregroundColor property.
	 * 
	 * @param value
	 *            allowed object is {@link java.lang.String }
	 * 
	 */
	public void setForegroundColor(java.lang.String value) {
		this.foregroundColor = value;
	}

	/**
	 * Gets the value of the backgroundColor property.
	 * 
	 * @return possible object is {@link java.lang.String }
	 * 
	 */
	public java.lang.String getBackgroundColor() {
		return backgroundColor;
	}

	/**
	 * Sets the value of the backgroundColor property.
	 * 
	 * @param value
	 *            allowed object is {@link java.lang.String }
	 * 
	 */
	public void setBackgroundColor(java.lang.String value) {
		this.backgroundColor = value;
	}

	/**
	 * Gets the value of the overrideURL property.
	 * 
	 * @return possible object is {@link java.lang.String }
	 * 
	 */
	public java.lang.String getOverrideURL() {
		return overrideURL;
	}

	/**
	 * Sets the value of the overrideURL property.
	 * 
	 * @param value
	 *            allowed object is {@link java.lang.String }
	 * 
	 */
	public void setOverrideURL(java.lang.String value) {
		this.overrideURL = value;
	}

	/**
	 * Gets the value of the tags property.
	 * 
	 * @return possible object is {@link java.lang.String }
	 * 
	 */
	public java.lang.String getTags() {
		return tags;
	}

	/**
	 * Sets the value of the tags property.
	 * 
	 * @param value
	 *            allowed object is {@link java.lang.String }
	 * 
	 */
	public void setTags(java.lang.String value) {
		this.tags = value;
	}

	/**
	 * Gets the value of the times property.
	 * 
	 * @return possible object is {@link Times }
	 * 
	 */
	public Times getTimes() {
		return times;
	}

	/**
	 * Sets the value of the times property.
	 * 
	 * @param value
	 *            allowed object is {@link Times }
	 * 
	 */
	public void setTimes(Times value) {
		this.times = value;
	}

	/**
	 * Gets the value of the string property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the string property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getString().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link Entry.String }
	 * 
	 * 
	 */
	public List<Entry.String> getString() {
		if (string == null) {
			string = new ArrayList<Entry.String>();
		}
		return this.string;
	}

	public void setString(List<Entry.String> value) {
		this.string = value;
	}

	/**
	 * Gets the value of the autoType property.
	 * 
	 * @return possible object is {@link Entry.AutoType }
	 * 
	 */
	public Entry.AutoType getAutoType() {
		return autoType;
	}

	/**
	 * Sets the value of the autoType property.
	 * 
	 * @param value
	 *            allowed object is {@link Entry.AutoType }
	 * 
	 */
	public void setAutoType(Entry.AutoType value) {
		this.autoType = value;
	}

	/**
	 * Gets the value of the history property.
	 * 
	 * @return possible object is {@link Entry.History }
	 * 
	 */
	public Entry.History getHistory() {
		return history;
	}

	/**
	 * Sets the value of the history property.
	 * 
	 * @param value
	 *            allowed object is {@link Entry.History }
	 * 
	 */
	public void setHistory(Entry.History value) {
		this.history = value;
	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="Enabled" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="DataTransferObfuscation" type="{http://www.w3.org/2001/XMLSchema}byte"/>
	 *         &lt;element name="DefaultSequence" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
	 *         &lt;element name="Association" maxOccurs="unbounded" minOccurs="0">
	 *           &lt;complexType>
	 *             &lt;complexContent>
	 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *                 &lt;sequence>
	 *                   &lt;element name="Window" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                   &lt;element name="KeystrokeSequence" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *                 &lt;/sequence>
	 *               &lt;/restriction>
	 *             &lt;/complexContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "enabled", "dataTransferObfuscation",
			"defaultSequence", "association" })
	public static class AutoType implements Serializable {

		/**
		 * 
		 */
		private static final long serialVersionUID = -258583265413157700L;
		@XmlElement(name = "Enabled", required = true)
		protected java.lang.String enabled;
		@XmlElement(name = "DataTransferObfuscation")
		protected byte dataTransferObfuscation;
		@XmlElement(name = "DefaultSequence")
		protected java.lang.String defaultSequence;
		@XmlElement(name = "Association")
		protected List<Entry.AutoType.Association> association;

		/**
		 * Gets the value of the enabled property.
		 * 
		 * @return possible object is {@link java.lang.String }
		 * 
		 */
		public java.lang.String getEnabled() {
			return enabled;
		}

		/**
		 * Sets the value of the enabled property.
		 * 
		 * @param value
		 *            allowed object is {@link java.lang.String }
		 * 
		 */
		public void setEnabled(java.lang.String value) {
			this.enabled = value;
		}

		/**
		 * Gets the value of the dataTransferObfuscation property.
		 * 
		 */
		public byte getDataTransferObfuscation() {
			return dataTransferObfuscation;
		}

		/**
		 * Sets the value of the dataTransferObfuscation property.
		 * 
		 */
		public void setDataTransferObfuscation(byte value) {
			this.dataTransferObfuscation = value;
		}

		/**
		 * Gets the value of the defaultSequence property.
		 * 
		 * @return possible object is {@link java.lang.String }
		 * 
		 */
		public java.lang.String getDefaultSequence() {
			return defaultSequence;
		}

		/**
		 * Sets the value of the defaultSequence property.
		 * 
		 * @param value
		 *            allowed object is {@link java.lang.String }
		 * 
		 */
		public void setDefaultSequence(java.lang.String value) {
			this.defaultSequence = value;
		}

		/**
		 * Gets the value of the association property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a
		 * snapshot. Therefore any modification you make to the returned list
		 * will be present inside the JAXB object. This is why there is not a
		 * <CODE>set</CODE> method for the association property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getAssociation().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list
		 * {@link Entry.AutoType.Association }
		 * 
		 * 
		 */
		public List<Entry.AutoType.Association> getAssociation() {
			if (association == null) {
				association = new ArrayList<Entry.AutoType.Association>();
			}
			return this.association;
		}

		/**
		 * <p>
		 * Java class for anonymous complex type.
		 * 
		 * <p>
		 * The following schema fragment specifies the expected content
		 * contained within this class.
		 * 
		 * <pre>
		 * &lt;complexType>
		 *   &lt;complexContent>
		 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		 *       &lt;sequence>
		 *         &lt;element name="Window" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *         &lt;element name="KeystrokeSequence" type="{http://www.w3.org/2001/XMLSchema}string"/>
		 *       &lt;/sequence>
		 *     &lt;/restriction>
		 *   &lt;/complexContent>
		 * &lt;/complexType>
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = { "window", "keystrokeSequence" })
		public static class Association implements Serializable{

			/**
			 * 
			 */
			private static final long serialVersionUID = 7955753060695120032L;
			@XmlElement(name = "Window", required = true)
			protected java.lang.String window;
			@XmlElement(name = "KeystrokeSequence", required = true)
			protected java.lang.String keystrokeSequence;

			/**
			 * Gets the value of the window property.
			 * 
			 * @return possible object is {@link java.lang.String }
			 * 
			 */
			public java.lang.String getWindow() {
				return window;
			}

			/**
			 * Sets the value of the window property.
			 * 
			 * @param value
			 *            allowed object is {@link java.lang.String }
			 * 
			 */
			public void setWindow(java.lang.String value) {
				this.window = value;
			}

			/**
			 * Gets the value of the keystrokeSequence property.
			 * 
			 * @return possible object is {@link java.lang.String }
			 * 
			 */
			public java.lang.String getKeystrokeSequence() {
				return keystrokeSequence;
			}

			/**
			 * Sets the value of the keystrokeSequence property.
			 * 
			 * @param value
			 *            allowed object is {@link java.lang.String }
			 * 
			 */
			public void setKeystrokeSequence(java.lang.String value) {
				this.keystrokeSequence = value;
			}

		}

	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="Entry" type="{}Entry" maxOccurs="unbounded" minOccurs="0"/>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "entry" })
	public static class History implements Serializable{

		/**
		 * 
		 */
		private static final long serialVersionUID = -3785398182691336030L;
		@XmlElement(name = "Entry")
		protected List<Entry> entry;

		/**
		 * Gets the value of the entry property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a
		 * snapshot. Therefore any modification you make to the returned list
		 * will be present inside the JAXB object. This is why there is not a
		 * <CODE>set</CODE> method for the entry property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getEntry().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list
		 * {@link Entry }
		 * 
		 * 
		 */
		public List<Entry> getEntry() {
			if (entry == null) {
				entry = new ArrayList<Entry>();
			}
			return this.entry;
		}

	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="Key" type="{http://www.w3.org/2001/XMLSchema}string"/>
	 *         &lt;element name="Value">
	 *           &lt;complexType>
	 *             &lt;simpleContent>
	 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
	 *                 &lt;attribute name="ProtectInMemory" type="{http://www.w3.org/2001/XMLSchema}string" />
	 *               &lt;/extension>
	 *             &lt;/simpleContent>
	 *           &lt;/complexType>
	 *         &lt;/element>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "key", "value" })
	public static class String implements Serializable{

		/**
		 * 
		 */
		private static final long serialVersionUID = 6856583166407946928L;
		@XmlElement(name = "Key", required = true)
		protected java.lang.String key;
		@XmlElement(name = "Value", required = true)
		protected java.lang.String value;

		/**
		 * Gets the value of the key property.
		 * 
		 * @return possible object is {@link java.lang.String }
		 * 
		 */
		public java.lang.String getKey() {
			return key;
		}

		/**
		 * Sets the value of the key property.
		 * 
		 * @param value
		 *            allowed object is {@link java.lang.String }
		 * 
		 */
		public void setKey(java.lang.String value) {
			this.key = value;
		}

		/**
		 * Gets the value of the value property.
		 * 
		 * @return possible object is {@link Entry.String.Value }
		 * 
		 */
		public java.lang.String getValue() {
			return value;
		}

		/**
		 * Sets the value of the value property.
		 * 
		 * @param value
		 *            allowed object is {@link Entry.String.Value }
		 * 
		 */
		public void setValue(java.lang.String value) {
			this.value = value;
		}

		/**
		 * <p>
		 * Java class for anonymous complex type.
		 * 
		 * <p>
		 * The following schema fragment specifies the expected content
		 * contained within this class.
		 * 
		 * <pre>
		 * &lt;complexType>
		 *   &lt;simpleContent>
		 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
		 *       &lt;attribute name="ProtectInMemory" type="{http://www.w3.org/2001/XMLSchema}string" />
		 *     &lt;/extension>
		 *   &lt;/simpleContent>
		 * &lt;/complexType>
		 * </pre>
		 * 
		 * 
		 */
		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = { "value" })
		public static class Value {

			@XmlValue
			protected java.lang.String value;
			@XmlAttribute(name = "ProtectInMemory")
			protected java.lang.String protectInMemory;

			/**
			 * Gets the value of the value property.
			 * 
			 * @return possible object is {@link java.lang.String }
			 * 
			 */
			public java.lang.String getValue() {
				return value;
			}

			/**
			 * Sets the value of the value property.
			 * 
			 * @param value
			 *            allowed object is {@link java.lang.String }
			 * 
			 */
			public void setValue(java.lang.String value) {
				this.value = value;
			}

			/**
			 * Gets the value of the protectInMemory property.
			 * 
			 * @return possible object is {@link java.lang.String }
			 * 
			 */
			public java.lang.String getProtectInMemory() {
				return protectInMemory;
			}

			/**
			 * Sets the value of the protectInMemory property.
			 * 
			 * @param value
			 *            allowed object is {@link java.lang.String }
			 * 
			 */
			public void setProtectInMemory(java.lang.String value) {
				this.protectInMemory = value;
			}

		}

	}

}
