//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.11 at 03:02:41 PM EDT 
//


package com.napoleoncs.keepass;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Group complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Group">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="UUID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Notes" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="IconID" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *         &lt;element name="Times" type="{}Times"/>
 *         &lt;element name="IsExpanded" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DefaultAutoTypeSequence" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="EnableAutoType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="EnableSearching" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="LastTopVisibleEntry" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Group" type="{}Group" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Entry" type="{}Entry" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Group", propOrder = {
    "uuid",
    "name",
    "notes",
    "iconID",
    "times",
    "isExpanded",
    "defaultAutoTypeSequence",
    "enableAutoType",
    "enableSearching",
    "lastTopVisibleEntry",
    "group",
    "entry"
})
public class Group {

    @XmlElement(name = "UUID", required = true)
    protected String uuid;
    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "Notes", required = true)
    protected String notes;
    @XmlElement(name = "IconID")
    protected byte iconID;
    @XmlElement(name = "Times", required = true)
    protected Times times;
    @XmlElement(name = "IsExpanded", required = true)
    protected String isExpanded;
    @XmlElement(name = "DefaultAutoTypeSequence", required = true)
    protected String defaultAutoTypeSequence;
    @XmlElement(name = "EnableAutoType", required = true)
    protected String enableAutoType;
    @XmlElement(name = "EnableSearching", required = true)
    protected String enableSearching;
    @XmlElement(name = "LastTopVisibleEntry", required = true)
    protected String lastTopVisibleEntry;
    @XmlElement(name = "Group")
    protected List<Group> group;
    @XmlElement(name = "Entry")
    protected List<Entry> entry;

    /**
     * Gets the value of the uuid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUUID() {
        return uuid;
    }

    /**
     * Sets the value of the uuid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUUID(String value) {
        this.uuid = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the notes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNotes() {
        return notes;
    }

    /**
     * Sets the value of the notes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNotes(String value) {
        this.notes = value;
    }

    /**
     * Gets the value of the iconID property.
     * 
     */
    public byte getIconID() {
        return iconID;
    }

    /**
     * Sets the value of the iconID property.
     * 
     */
    public void setIconID(byte value) {
        this.iconID = value;
    }

    /**
     * Gets the value of the times property.
     * 
     * @return
     *     possible object is
     *     {@link Times }
     *     
     */
    public Times getTimes() {
        return times;
    }

    /**
     * Sets the value of the times property.
     * 
     * @param value
     *     allowed object is
     *     {@link Times }
     *     
     */
    public void setTimes(Times value) {
        this.times = value;
    }

    /**
     * Gets the value of the isExpanded property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsExpanded() {
        return isExpanded;
    }

    /**
     * Sets the value of the isExpanded property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsExpanded(String value) {
        this.isExpanded = value;
    }

    /**
     * Gets the value of the defaultAutoTypeSequence property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultAutoTypeSequence() {
        return defaultAutoTypeSequence;
    }

    /**
     * Sets the value of the defaultAutoTypeSequence property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultAutoTypeSequence(String value) {
        this.defaultAutoTypeSequence = value;
    }

    /**
     * Gets the value of the enableAutoType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnableAutoType() {
        return enableAutoType;
    }

    /**
     * Sets the value of the enableAutoType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnableAutoType(String value) {
        this.enableAutoType = value;
    }

    /**
     * Gets the value of the enableSearching property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnableSearching() {
        return enableSearching;
    }

    /**
     * Sets the value of the enableSearching property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnableSearching(String value) {
        this.enableSearching = value;
    }

    /**
     * Gets the value of the lastTopVisibleEntry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastTopVisibleEntry() {
        return lastTopVisibleEntry;
    }

    /**
     * Sets the value of the lastTopVisibleEntry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastTopVisibleEntry(String value) {
        this.lastTopVisibleEntry = value;
    }

    /**
     * Gets the value of the group property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the group property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Group }
     * 
     * 
     */
    public List<Group> getGroup() {
        if (group == null) {
            group = new ArrayList<Group>();
        }
        return this.group;
    }
    
    public void setGroup(List<Group> value){
    	this.group = value;
    }

    /**
     * Gets the value of the entry property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the entry property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEntry().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Entry }
     * 
     * 
     */
    public List<Entry> getEntry() {
        if (entry == null) {
            entry = new ArrayList<Entry>();
        }
        return this.entry;
    }
    
    public void setEntry(List<Entry> value){
    	this.entry = value;
    }

}
