//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.11 at 03:02:41 PM EDT 
//


package com.napoleoncs.keepass;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.napoleoncs.keepass package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.napoleoncs.keepass
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Entry }
     * 
     */
    public Entry createEntry() {
        return new Entry();
    }

    /**
     * Create an instance of {@link Entry.AutoType }
     * 
     */
    public Entry.AutoType createEntryAutoType() {
        return new Entry.AutoType();
    }

    /**
     * Create an instance of {@link Entry.String }
     * 
     */
    public Entry.String createEntryString() {
        return new Entry.String();
    }

    /**
     * Create an instance of {@link Root }
     * 
     */
    public Root createRoot() {
        return new Root();
    }

    /**
     * Create an instance of {@link Root.DeletedObjects }
     * 
     */
    public Root.DeletedObjects createRootDeletedObjects() {
        return new Root.DeletedObjects();
    }

    /**
     * Create an instance of {@link Meta }
     * 
     */
    public Meta createMeta() {
        return new Meta();
    }

    /**
     * Create an instance of {@link Meta.CustomIcons }
     * 
     */
    public Meta.CustomIcons createMetaCustomIcons() {
        return new Meta.CustomIcons();
    }

    /**
     * Create an instance of {@link KeePassFile }
     * 
     */
    public KeePassFile createKeePassFile() {
        return new KeePassFile();
    }

    /**
     * Create an instance of {@link Times }
     * 
     */
    public Times createTimes() {
        return new Times();
    }

    /**
     * Create an instance of {@link Group }
     * 
     */
    public Group createGroup() {
        return new Group();
    }

    /**
     * Create an instance of {@link Entry.History }
     * 
     */
    public Entry.History createEntryHistory() {
        return new Entry.History();
    }

    /**
     * Create an instance of {@link Entry.AutoType.Association }
     * 
     */
    public Entry.AutoType.Association createEntryAutoTypeAssociation() {
        return new Entry.AutoType.Association();
    }

    /**
     * Create an instance of {@link Entry.String.Value }
     * 
     */
    public Entry.String.Value createEntryStringValue() {
        return new Entry.String.Value();
    }

    /**
     * Create an instance of {@link Root.DeletedObjects.DeletedObject }
     * 
     */
    public Root.DeletedObjects.DeletedObject createRootDeletedObjectsDeletedObject() {
        return new Root.DeletedObjects.DeletedObject();
    }

    /**
     * Create an instance of {@link Meta.MemoryProtection }
     * 
     */
    public Meta.MemoryProtection createMetaMemoryProtection() {
        return new Meta.MemoryProtection();
    }

    /**
     * Create an instance of {@link Meta.CustomIcons.Icon }
     * 
     */
    public Meta.CustomIcons.Icon createMetaCustomIconsIcon() {
        return new Meta.CustomIcons.Icon();
    }

}
